apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: python3-devspaces 
  janus-idp.io/tekton: python3-devspaces
  backstage.io/kubernetes-id: python3-devspaces
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: python3-devspaces
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  