apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: python3-devspaces
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python3-devspaces 
  name: python3-devspaces
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: python3-devspaces 
